### ISSUE TITLE
1/10코드리뷰 이후 나온 해결해야 할 것들

### ISSUE THREAD

**Issue by Dongjun-Jii** [Team-QSS/DSEngine#2]
Object에서 Exist 랑 get
Object, Scene 소멸자
소멸시 가진 컨테이너들 전체 비움
Scene클래스에서 가비지컬렉터 만들기
DSEngine의 최초 씬 변경

**Comment by usernameSplash** [comment]
1/15
Scene소멸자,
Scene클래스에서 가비지 컬렉터 구현 완료

**Comment by usernameSplash** [comment]
가비지 컬렉터에서 마지막에 Garbage 컨테이너 clear 필요
void collectGarbage() 메서드에서 if문 조건 기술 시 이미 구현한 exist 메서드를 재활용하면 좋을 듯
